# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- api

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core sdk 6.x'
  inputs:
    packageType: 'sdk'
    version: 6.x

- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: 'restore'
    projects: |
      **/Ebd.Domain.Core.csproj
      **/Ebd.Infra.Data.csproj
      **/Ebd.CrossCutting.IoC.csproj
      **/Ebd.Application.csproj
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: |
      **/Ebd.Domain.Core.csproj
      **/Ebd.Infra.Data.csproj
      **/Ebd.CrossCutting.IoC.csproj
      **/Ebd.Application.csproj
    arguments: '-o $(Build.ArtifactStagingDirectory)'

- task: DotNetCoreCLI@2
  displayName: 'Publish files'
  inputs:
    command: 'publish'
    projects: '**/Ebd.Presentation.Api.csproj'
    publishWebProjects: true
    arguments: '-o $(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts $(Build.ArtifactStagingDirectory)'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: AzureRmWebAppDeployment@4
  displayName: Deploy on admp.azurewebsites.net
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'GTech(1)(b42a60f5-3c02-4a26-851c-36d2273fb56a)'
    appType: 'webApp'
    WebAppName: 'admp'
    packageForLinux: '$(System.ArtifactStagingDirectory)/**/*.zip'
